<?php echo $this->tag->form(['user/add', 'class' => 'form-horizontal']); ?>
  <div class="form-group">
    <label class="control-label col-sm-2" for="username" required>Username:</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="username" placeholder="Enter username" name="username">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="nama" required>Name:</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="nama" placeholder="Enter name" name="nama">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="email" required>Email:</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="pwd" required>Password:</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pass">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign Up</button>
    </div>
  </div>
</form>