<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon Esha</title>
        <link rel="stylesheet" href="<?php echo $this->url->get('css/bootstrap.min.css')?>"/>
        <link rel="stylesheet" href="<?php echo $this->url->get('css/jumbotron-narrow.css')?>"/>
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
        <div class="container">
          <div class="header clearfix">
            <nav>
              <ul class="nav nav-pills pull-right">
                <li role="presentation"><?php echo $this->tag->linkTo('','Home'); ?></li>
                <li role="presentation"><?php echo $this->tag->linkTo('user','User'); ?></li>
              </ul>
            </nav>
            <h3 class="text-muted">Phalcon esha</h3>
          </div>

          <div class="row marketing">
            <?php echo $this->getContent(); ?>
          </div>

          <footer class="footer">
            <p>&copy; Esha 2018.</p>
          </footer>

        </div> <!-- /container -->
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="<?php echo $this->url->get('js/bootstrap.min.js')?>"></script>
    </body>
</html>
